packages:
  - .

overrides:
  vite: "catalog:"
  vitest: "catalog:"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@^0.3.0
  vitest: 4.1.11
  vite-plus: ^0.3.0
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
allowBuilds:
  agent-browser: true
  esbuild: true
minimumReleaseAgeExclude:
  - "@sveltejs/adapter-node@6.0.0-next.4"
  - "@sveltejs/kit@3.0.0-next.10"
